TYPE=VIEW
query=select `l`.`titre_livre` AS `titre_livre`,`l`.`nombre_page` AS `nombre_page`,`g`.`nom_genre` AS `nom_genre`,`v`.`code_postal` AS `code_postal`,`v`.`ville` AS `ville`,`l`.`image` AS `image`,`u`.`pseudo` AS `pseudo`,`e`.`integrite_du_livre` AS `integrite_du_livre`,`p`.`date_retour` AS `date_retour`,`e`.`isbn` AS `isbn`,`a`.`nom_a` AS `nom_a`,`a`.`prenom` AS `prenom`,`a`.`id_auteur` AS `id_auteur` from (((((((`filrougev3`.`livre` `l` join `filrougev3`.`exemplaire` `e` on((`e`.`isbn` = `l`.`isbn`))) join `filrougev3`.`genre` `g` on((`g`.`id_genre` = `l`.`id_genre`))) join `filrougev3`.`posseder` `p` on((`p`.`id_exemplaire` = `e`.`id_exemplaire`))) join `filrougev3`.`users` `u` on((`u`.`id` = `p`.`id`))) join `filrougev3`.`ville` `v` on((`v`.`id_ville` = `u`.`id_ville`))) join `filrougev3`.`ecrit` `ec` on((`ec`.`isbn` = `e`.`isbn`))) join `filrougev3`.`auteur` `a` on((`a`.`id_auteur` = `ec`.`id_auteur`))) where `p`.`date_retour` in (select max(`filrougev3`.`posseder`.`date_retour`) AS `date_retour` from `filrougev3`.`posseder` where (not(`filrougev3`.`posseder`.`id_exemplaire` in (select `filrougev3`.`posseder`.`id_exemplaire` from `filrougev3`.`posseder` where isnull(`filrougev3`.`posseder`.`date_retour`)))) group by `filrougev3`.`posseder`.`id_exemplaire`)
md5=082fac839af76869fb8c6dca948e04b7
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2021-05-21 07:57:02
create-version=1
source=SELECT\n    `l`.`titre_livre` AS `titre_livre`,\n    `l`.`nombre_page` AS `nombre_page`,\n    `g`.`nom_genre` AS `nom_genre`,\n    `v`.`code_postal` AS `code_postal`,\n    `v`.`ville` AS `ville`,\n    `l`.`image` AS `image`,\n    `u`.`pseudo` AS `pseudo`,\n    `e`.`integrite_du_livre` AS `integrite_du_livre`,\n    `p`.`date_retour` AS `date_retour`,\n    `e`.`isbn` AS `isbn`,\n    `a`.`nom_a` AS `nom_a`,\n    `a`.`prenom` AS `prenom`,\n    `a`.`id_auteur` AS `id_auteur`\nFROM\n    (\n        (\n            (\n                (\n                    (\n                        (\n                            (\n                                `filrougev3`.`livre` `l`\n                            JOIN `filrougev3`.`exemplaire` `e`\n                            ON\n                                ((`e`.`isbn` = `l`.`isbn`))\n                            )\n                        JOIN `filrougev3`.`genre` `g`\n                        ON\n                            ((`g`.`id_genre` = `l`.`id_genre`))\n                        )\n                    JOIN `filrougev3`.`posseder` `p`\n                    ON\n                        (\n                            (\n                                `p`.`id_exemplaire` = `e`.`id_exemplaire`\n                            )\n                        )\n                    )\n                JOIN `filrougev3`.`users` `u`\n                ON\n                    ((`u`.`id` = `p`.`id`))\n                )\n            JOIN `filrougev3`.`ville` `v`\n            ON\n                ((`v`.`id_ville` = `u`.`id_ville`))\n            )\n        JOIN `filrougev3`.`ecrit` `ec`\n        ON\n            ((`ec`.`isbn` = `e`.`isbn`))\n        )\n    JOIN `filrougev3`.`auteur` `a`\n    ON\n        ((`a`.`id_auteur` = `ec`.`id_auteur`))\n    )\nWHERE\n    `p`.`date_retour` IN(\n    SELECT\n        MAX(\n            `filrougev3`.`posseder`.`date_retour`\n        ) AS `date_retour`\n    FROM\n        `filrougev3`.`posseder`\n    WHERE\n        (\n            NOT(\n                `filrougev3`.`posseder`.`id_exemplaire` IN(\n                SELECT\n                    `filrougev3`.`posseder`.`id_exemplaire`\n                FROM\n                    `filrougev3`.`posseder`\n                WHERE\n                    ISNULL(\n                        `filrougev3`.`posseder`.`date_retour`\n                    )\n            )\n            )\n        )\n    GROUP BY\n        `filrougev3`.`posseder`.`id_exemplaire`\n)
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `l`.`titre_livre` AS `titre_livre`,`l`.`nombre_page` AS `nombre_page`,`g`.`nom_genre` AS `nom_genre`,`v`.`code_postal` AS `code_postal`,`v`.`ville` AS `ville`,`l`.`image` AS `image`,`u`.`pseudo` AS `pseudo`,`e`.`integrite_du_livre` AS `integrite_du_livre`,`p`.`date_retour` AS `date_retour`,`e`.`isbn` AS `isbn`,`a`.`nom_a` AS `nom_a`,`a`.`prenom` AS `prenom`,`a`.`id_auteur` AS `id_auteur` from (((((((`filrougev3`.`livre` `l` join `filrougev3`.`exemplaire` `e` on((`e`.`isbn` = `l`.`isbn`))) join `filrougev3`.`genre` `g` on((`g`.`id_genre` = `l`.`id_genre`))) join `filrougev3`.`posseder` `p` on((`p`.`id_exemplaire` = `e`.`id_exemplaire`))) join `filrougev3`.`users` `u` on((`u`.`id` = `p`.`id`))) join `filrougev3`.`ville` `v` on((`v`.`id_ville` = `u`.`id_ville`))) join `filrougev3`.`ecrit` `ec` on((`ec`.`isbn` = `e`.`isbn`))) join `filrougev3`.`auteur` `a` on((`a`.`id_auteur` = `ec`.`id_auteur`))) where `p`.`date_retour` in (select max(`filrougev3`.`posseder`.`date_retour`) AS `date_retour` from `filrougev3`.`posseder` where (not(`filrougev3`.`posseder`.`id_exemplaire` in (select `filrougev3`.`posseder`.`id_exemplaire` from `filrougev3`.`posseder` where isnull(`filrougev3`.`posseder`.`date_retour`)))) group by `filrougev3`.`posseder`.`id_exemplaire`)
